const sampleTrades = [
    {
      id: 1,
      dateCreated: 'Mon, Jan 10 at 15:30',
      eventName: 'Golden State Warriors vs Memphis',
      eventStartDate: 'Mon, Jan 10 at 18:00',
      marketName: 'Player Assists',
      betName: 'Ja Morant Under 8.5',
      clv: 2.5,
      odds: -2.0,
      stake: 50.0,
      status: 'Win',
    },
    {
      id: 2,
      dateCreated: 'Tue, Jan 11 at 12:45',
      eventName: 'Los Angeles Lakers vs Boston Celtics',
      eventStartDate: 'Tue, Jan 11 at 14:30',
      marketName: 'Total Points',
      betName: 'Over 215.5',
      clv: 1.8,
      odds: -1.9,
      stake: 75.0,
      status: 'Loss',
    },
    {
      id: 3,
      dateCreated: 'Wed, Jan 12 at 09:15',
      eventName: 'Chicago Bulls vs Miami Heat',
      eventStartDate: 'Wed, Jan 12 at 11:00',
      marketName: 'Player Points',
      betName: 'Jimmy Butler Over 25.5',
      clv: 3.0,
      odds: 2.5,
      stake: 40.0,
      status: 'In Progress',
    },
    {
      id: 4,
      dateCreated: 'Thu, Jan 13 at 16:00',
      eventName: 'Houston Rockets vs Toronto Raptors',
      eventStartDate: 'Thu, Jan 13 at 18:30',
      marketName: 'Three-Pointers',
      betName: 'Kyle Lowry Over 3.5',
      clv: 2.2,
      odds: -1.8,
      stake: 60.0,
      status: 'Loss',
    },
    {
      id: 5,
      dateCreated: 'Fri, Jan 14 at 14:00',
      eventName: 'Dallas Mavericks vs Phoenix Suns',
      eventStartDate: 'Fri, Jan 14 at 16:30',
      marketName: 'Rebounds',
      betName: 'Deandre Ayton Over 10.5',
      clv: 2.8,
      odds: 2.2,
      stake: 55.0,
      status: 'Draw',
    },
    {
      id: 6,
      dateCreated: 'Sat, Jan 15 at 11:30',
      eventName: 'Brooklyn Nets vs Atlanta Hawks',
      eventStartDate: 'Sat, Jan 15 at 14:00',
      marketName: 'Assist + Points + Rebounds',
      betName: 'Trae Young Over 35.5',
      clv: 2.5,
      odds: 2.3,
      stake: 65.0,
      status: 'Win',
    },
    {
      id: 7,
      dateCreated: 'Sun, Jan 16 at 13:00',
      eventName: 'Orlando Magic vs New York Knicks',
      eventStartDate: 'Sun, Jan 16 at 15:30',
      marketName: 'Steals',
      betName: 'RJ Barrett Over 1.5',
      clv: 2.0,
      odds: -1.7,
      stake: 45.0,
      status: 'In Progress',
    },
    {
      id: 8,
      dateCreated: 'Mon, Jan 17 at 10:45',
      eventName: 'Utah Jazz vs Indiana Pacers',
      eventStartDate: 'Mon, Jan 17 at 13:15',
      marketName: 'Blocks',
      betName: 'Rudy Gobert Over 2.5',
      clv: 2.3,
      odds: -2.1,
      stake: 70.0,
      status: 'In Progress',
    },
    {
      id: 9,
      dateCreated: 'Tue, Jan 18 at 14:30',
      eventName: 'Minnesota Timberwolves vs Detroit Pistons',
      eventStartDate: 'Tue, Jan 18 at 17:00',
      marketName: 'Field Goals',
      betName: 'Cade Cunningham Over 5.5',
      clv: 2.7,
      odds: 2.0,
      stake: 50.0,
      status: 'Pending',
    },
    {
      id: 10,
      dateCreated: 'Wed, Jan 19 at 18:00',
      eventName: 'San Antonio Spurs vs Charlotte Hornets',
      eventStartDate: 'Wed, Jan 19 at 20:30',
      marketName: 'Points',
      betName: 'LaMelo Ball Over 22.5',
      clv: 2.4,
      odds: 2.2,
      stake: 60.0,
      status: 'Pending',
    },
  ];
  
  export default sampleTrades;