// login
export const LOGIN_INIT = "LOGIN_INIT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// sign-up
export const SIGN_UP_INIT = "SIGN_UP_INIT";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

// Google Sign-in
export const GOOGLE_SIGNIN_INIT = "GOOGLE_SIGNIN_INIT";
export const GOOGLE_SIGNIN_SUCCESS = "GOOGLE_SIGNIN_SUCCESS";
export const GOOGLE_SIGNIN_FAILURE = "GOOGLE_SIGNIN_FAILURE";

// Upload Photo
export const UPLOAD_PHOTO_INIT = "UPLOAD_PHOTO_INIT";
export const UPLOAD_PHOTO_SUCCESS = "UPLOAD_PHOTO_SUCCESS";
export const UPLOAD_PHOTO_FAILURE = "UPLOAD_PHOTO_FAILURE";

// Reset Password
export const RESET_PASSWORD_INIT = "RESET_PASSWORD_INIT";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

// Reset Confirm Password
export const RESET_CONFIRM_PASSWORD_INIT = "RESET_CONFIRM_PASSWORD_INIT";
export const RESET_CONFIRM_PASSWORD_SUCCESS = "RESET_CONFIRM_PASSWORD_SUCCESS";
export const RESET_CONFIRM_PASSWORD_FAILURE = "RESET_CONFIRM_PASSWORD_FAILURE";

// Change Password
export const CHANGE_PASSWORD_INIT = "CHANGE_PASSWORD_INIT";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

// Add Card Details
export const ADD_CARD_DETAILS_INIT = "ADD_CARD_DETAILS_INIT";
export const ADD_CARD_DETAILS_SUCCESS = "ADD_CARD_DETAILS_SUCCESS";
export const ADD_CARD_DETAILS_FAILURE = "ADD_CARD_DETAILS_FAILURE";

// User Profile
export const USER_PROFILE_INIT = "USER_PROFILE_INIT";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";

// User Kyc Info
export const USER_KYC_INFO_INIT = "USER_KYC_INFO_INIT";
export const USER_KYC_INFO_SUCCESS = "USER_KYC_INFO_SUCCESS";
export const USER_KYC_INFO_FAILURE = "USER_KYC_INFO_FAILURE";

// Send Feedback
export const SEND_FEEDBACK_INIT = "SEND_FEEDBACK_INIT";
export const SEND_FEEDBACK_SUCCESS = "SEND_FEEDBACK_SUCCESS";
export const SEND_FEEDBACK_FAILURE = "SEND_FEEDBACK_FAILURE";

// Update User
export const UPDATE_USER_INIT = "UPDATE_USER_INIT";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

//Email Verification
export const EMAIL_VERIFICATION_INIT = "EMAIL_VERIFICATION_INIT";
export const EMAIL_VERIFICATION_SUCCESS = "EMAIL_VERIFICATION_SUCCESS";
export const EMAIL_VERIFICATION_FAILURE = "EMAIL_VERIFICATION_FAILURE";
// Betting History
export const BETTING_HISTORY_INIT = "BETTING_HISTORY_INIT";
export const BETTING_HISTORY_SUCCESS = "BETTING_HISTORY_SUCCESS";
export const BETTING_HISTORY_FAILURE = "BETTING_HISTORY_FAILURE";

// Payment History
export const PAYMENT_HISTORY_INIT = "PAYMENT_HISTORY_INIT";
export const PAYMENT_HISTORY_SUCCESS = "PAYMENT_HISTORY_SUCCESS";
export const PAYMENT_HISTORY_FAILURE = "PAYMENT_HISTORY_FAILURE";

// Transaction
export const TRANSACTION_INIT = "TRANSACTION_INIT";
export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
export const TRANSACTION_FAILURE = "TRANSACTION_FAILURE";

// Email Verification
export const EMAIL_CHANGE_VERIFY_INIT = "EMAIL_CHANGE_VERIFY_INIT";
export const EMAIL_CHANGE_VERIFY_SUCCESS = "EMAIL_CHANGE_VERIFY_SUCCESS";
export const EMAIL_CHANGE_VERIFY_FAILURE = "EMAIL_CHANGE_VERIFY_FAILURE";
// KYC FORM
export const KYC_FORM_INIT = "KYC_FORM_INIT";
export const KYC_FORM_SUCCESS = "KYC_FORM_SUCCESS";
export const KYC_FORM_FAILURE = "KYC_FORM_FAILURE";

// SURVEY FORM
export const SURVEY_FORM_INIT = "SURVEY_FORM_INIT";
export const SURVEY_FORM_SUCCESS = "SURVEY_FORM_SUCCESS";
export const SURVEY_FORM_FAILURE = "SURVEY_FORM_FAILURE";

// FUNDED TRADER
export const FUNDED_TRADER_INIT = "FUNDED_TRADER_INIT";
export const FUNDED_TRADER_SUCCESS = "FUNDED_TRADER_SUCCESS";
export const FUNDED_TRADER_FAILURE = "FUNDED_TRADER_FAILURE";

// Sports Games
export const SPORTS_GAMES_INIT = "SPORTS_GAMES_INIT";
export const SPORTS_GAMES_SUCCESS = "SPORTS_GAMES_SUCCESS";
export const SPORTS_GAMES_FAILURE = "SPORTS_GAMES_FAILURE";

// Sports
export const SPORTS_INIT = "SPORTS_INIT";
export const SPORTS_SUCCESS = "SPORTS_SUCCESS";
export const SPORTS_FAILURE = "SPORTS_FAILURE";

// Payment
export const PAYMENT_INIT = "PAYMENT_INIT";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAILURE = "PAYMENT_FAILURE";

// User Token
export const USER_TOKEN_SUCCESS = "USER_TOKEN_SUCCESS";
export const USER_TOKEN_FAILURE = "USER_TOKEN_FAILURE";

//Logout
export const CLEAR_REDUX_STATE = "CLEAR_REDUX_STATE"

// Place Bet
export const PLACE_BET_INIT = "PLACE_BET_INIT";
export const PLACE_BET_SUCCESS = "PLACE_BET_SUCCESS";
export const PLACE_BET_FAILURE = "PLACE_BET_FAILURE";
// Leaderboard
export const LEADERBOARD_INIT = "LEADERBOARD_INIT";
export const LEADERBOARD_SUCCESS = "LEADERBOARD_SUCCESS";
export const LEADERBOARD_FAILURE = "LEADERBOARD_FAILURE";

// Notifications
export const NOTIFICATIONS_INIT = "NOTIFICATIONS_INIT";
export const NOTIFICATIONS_SUCCESS = "NOTIFICATIONS_SUCCESS";
export const NOTIFICATIONS_FAILURE = "NOTIFICATIONS_FAILURE";

// All Subscription Packages
export const PACKAGES_LIST_INIT = "PACKAGES_LIST_INIT";
export const PACKAGES_LIST_SUCCESS = "PACKAGES_LIST_SUCCESS";
export const PACKAGES_LIST_FAILURE = "PACKAGES_LIST_FAILURE";

// Subscription Plan List
export const SUBSCRIPTION_PLAN_INIT = "SUBSCRIPTION_PLAN_INIT";
export const SUBSCRIPTION_PLAN_SUCCESS = "SUBSCRIPTION_PLAN_SUCCESS";
export const SUBSCRIPTION_PLAN_FAILURE = "SUBSCRIPTION_PLAN_FAILURE";

// Purchase Package Subscription Plan List
export const PURCHASE_PACKAGE_INIT = "PURCHASE_PACKAGE_INIT";
export const PURCHASE_PACKAGE_SUCCESS = "PURCHASE_PACKAGE_SUCCESS";
export const PURCHASE_PACKAGE_FAILURE = "PURCHASE_PACKAGE_FAILURE";

// Withdrawal
export const WITHDRAWAL_INIT = "WITHDRAWAL_INIT";
export const WITHDRAWAL_SUCCESS = "WITHDRAWAL_SUCCESS";
export const WITHDRAWAL_FAILURE = "WITHDRAWAL_FAILURE";

// Challange Status
export const CHALLANGE_STATUS_INIT = "CHALLANGE_STATUS_INIT";
export const CHALLANGE_STATUS_SUCCESS = "CHALLANGE_STATUS_SUCCESS";
export const CHALLANGE_STATUS_FAILURE = "CHALLANGE_STATUS_FAILURE";

// Advance Statistics
export const ADVANCE_STATISTICS_INIT = "ADVANCE_STATISTICS_INIT";
export const ADVANCE_STATISTICS_SUCCESS = "ADVANCE_STATISTICS_SUCCESS";
export const ADVANCE_STATISTICS_FAILURE = "ADVANCE_STATISTICS_FAILURE";

// Delete Account
export const DELETE_INIT = "DELETE_INIT";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILURE = "DELETE_FAILURE";

// Discount Apply
export const DISCOUNT_APPLY_INIT = "DISCOUNT_APPLY_INIT";
export const DISCOUNT_APPLY_SUCCESS = "DISCOUNT_APPLY_SUCCESS";
export const DISCOUNT_APPLY_FAILURE = "DISCOUNT_APPLY_FAILURE";

// POST FCM TOKEN
export const POST_FCM_INIT = "POST_FCM_INIT";
export const POST_FCM_SUCCESS = "POST_FCM_SUCCESS";
export const POST_FCM_FAILURE = "POST_FCM_FAILURE";

// GET NOTIFICATION
export const GET_NOTIFICATION_INIT = "GET_NOTIFICATION_INIT";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_FAILURE = "GET_NOTIFICATION_FAILURE";